language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django110
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 2.7
      env: TOXENV=py27-flask
    - python: 2.7
      env: TOXENV=py27-celery
    - python: 3.5
      env: TOXENV=py35-django110
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.5
      env: TOXENV=py35-flask
    - python: 3.5
      env: TOXENV=py35-celery
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.6
      env: TOXENV=py36-flask
    - python: 3.6
      env: TOXENV=py36-celery
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-django20
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-django21
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-flask
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-celery
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=flake8
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=black
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=isort
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=doc8
cache: pip
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov
