language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
cache:
  directories:
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -U pip wheel
  - pip install .
  - pip install -r requirements/qa.txt
  - pip install -r requirements/ci.txt
script:
  - coverage run -m pytest
after_success:
  - coveralls
