language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django10
    - python: 2.7
      env: TOXENV=py27-django11
    - python: 3.5
      env: TOXENV=py35-django10
    - python: 3.5
      env: TOXENV=py35-django11
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django11
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-django20
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-django21
cache: pip
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov
